services:
  server:
    image: image-backend-ldla-dev
    build:
      context: .
    environment:
      NODE_ENV: production
      <ENV_VARIABLE_FOR_MONGO_URI>: "mongodb+srv://admin-dev-ldla:DevAdminDataBase2024@devsiteldlacluster.xtpuzzh.mongodb.net/?"
    container_name: backend-ldla-dev
    ports: 
      - 8100:8100
    command: >
      sh -c "npm start"
    volumes:
      - .:/backend-ldla-dev
